version: '3'
services:
  detector:
    build:
      context: ./object-detector
    ports:
      - "8888:8888"
    depends_on:
      - flask-server

  flask-server:
    build:
      context: ./flask-post-processing
    ports:
      - "5555:5555"
