version: '3'
services:
  # kafka:
  #   image: bitnami/kafka:3.7
  #   container_name: kafka
  #   ports:
  #     - "9092:9092"
  #   environment:
  #     - KAFKA_CFG_MESSAGE_MAX_BYTES=10485760
  #     - KAFKA_CFG_REPLICA_FETCH_MAX_BYTES=10485760
  #     - KAFKA_CFG_MAX_REQUEST_SIZE=10485760
  #     - KAFKA_ENABLE_KRAFT=yes
  #     - KAFKA_CFG_NODE_ID=1
  #     - KAFKA_CFG_PROCESS_ROLES=controller,broker
  #     - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
  #     - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
  #     - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
  #     - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
  #     - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
  #     - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
  detector:
    build:
      context: ./object-detector

  # flask-server:
  #   build:
  #     context: ./flask-post-processing
  #   ports:
  #     - "5555:5555"
  #   env_file:
  #     - .env

  # video-stream:
  #   build:
  #     context: ./video-ingestion

  sending-frames:
    build:
      context: ./kafka-sending-script
    restart: always



